### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/firmware#15]
Die Knoten sollen ein (ständiges?) Web-Interface bekommen bei dem man z.B. folgende Dinge einstellen können soll:
* Hostname
* Geo-Koordinaten
* SSH Passwort
* Hood(?)
* Autoupdater (An/Aus, Server)
* privates WLAN (An/Aus SSID)
* Traffic-Shaping
* Switch Konfiguration (LEDs blinken lassen!?)
* usw.

**Comment by kratz00** [comment]
Der erste Schritt ist gemacht: bd9420b5fb94650a51e38a29f046bc96e943f365
