### ISSUE TITLE
/etc/passwd falsch nach Update

### ISSUE THREAD

**Issue by IVI053** [FreifunkFranken/firmware#20]
Ich musste feststellen, dass, obwohl wir shadow, benutzen nach einem Update in der passwd nicht mehr `root:x:...` steht. Vor dem Update stand es dort und nach dem nutzen von `passwd` und einem erneuten Setzen steht es auch wieder dort. SSH scheint dies nicht zu beinflussen, aber `/bin/login` auf meinem Testgerät. Dieses verweigert nämlich aufgrund falschem Passwort. Ich vermute das es sich genau an dieser Stelle aufstößt.

Hier ein Beispiel

    root@OpenWrt:/# cat /etc/passwd
    root:$1$OmvoKpjK$e.lPVnBxsrAbNV4EoH3xb1:0:0:root:/root:/bin/ash
    nobody:*:65534:65534:nobody:/var:/bin/false
    daemon:*:65534:65534:daemon:/var:/bin/false
    
    root@OpenWrt:/# cat /etc/shadow
    root:$1$9WY3tbCn$fPofdIgRtoPX4WLDpsBqk0:16385:0:99999:7:::
    daemon:*:0:0:99999:7:::
    ftp:*:0:0:99999:7:::
    network:*:0:0:99999:7:::
    nobody:*:0:0:99999:7:::

Kann dieses Verhalten jemand bestätigen?

**Comment by kratz00** [comment]
Ich konnte es nachstellen und habe es behoben (siehe a275253155bde7969272311efe124420da152aa0).
