### ISSUE TITLE
wr841nd v7 Problem mit network.tl-wr841nd-v7

### ISSUE THREAD

**Issue by ChristianDresel** [FreifunkFranken/firmware#25]
hi

wenn man das wr841nd V7 auf einen entsprechenden Router flasht, wird auf dem Router nach der File network.tl-wr841n-v7 (obwohl es sich um einen nd handelt!) gesucht welche nicht vorhanden ist. Es gibt die Datei network.tl-wr841n-v7 welche die richtige wäre. Manuelles unbenennen (SSH per locallink welcher zum Glück geht) behebt das Problem und der Router kann danach verwendet werden.

v8 und v9 scheinen das Problem nicht zu haben.

Gruß Christian

**Comment by meskal** [comment]
Dieses Problem ist seit Commit https://github.com/FreifunkFranken/firmware/commit/c1c8434c329001869d7d50fd688c421b81918b7e behoben. Leider aber eben noch nicht in einem Release verbaut. Allerdings sollte es mit der pre-release hier gehen:
https://dev.freifunk-franken.de/firmware/dev/20150907_meskal/
Das sollte man vielleicht mal im Wiki dokumentieren.
