### ISSUE TITLE
Keine IP-Vergabe mit Firmware 0.5.1 und TP-Link WR841N v9.0

### ISSUE THREAD

**Issue by luwimi** [FreifunkFranken/firmware#27]
Ich habe einen 841 mit 9.0er Hardware von Braunschweiger Firmware auf die Franken-Frimware 0.5.1 umgeflasht (sysupgrade). Das gleiche habe ich mit einer 8.xer Hardware auch getan (Router km001  [8.x] und km010 [9.0] https://netmon.freifunk-franken.de/router.php?router_id=1647) Bei der 8.xer Hardware gab es keine Probleme. 

Der 9.0er wurde problemlos im Netmon aufgenommen, und meshte. Jedoch war das einloggen ins WLAN mit einem Client nicht möglich. Allem Anschein nach wurde keine IP vergeben.

Ein Downgrade auf 0.5.0 scheint Abhilfe geschaffen zu haben.

Kann jemand den Fehler bestätigen oder dürfte es sich um ein Hardwareproblem handeln?

**Comment by jonasbebe** [comment]
Ich habe hier das selbe Problem, seit ca. einer Woche bekommen Endgeräte keine IP mehr. Das Problem besteht bei mir an den Routern "KJBuehl1" und "RZK5", beides WRD1043nd Rev. 2.1 Zeit zum gucken woran es liegen könnte, hatte ich bisher leider nicht.

**Comment by ChristianDresel** [comment]
Am 06.11.2015 um 20:46 schrieb luwimi:
>
> Ich habe einen 841 mit 9.0er Hardware von Braunschweiger Firmware auf 
> die Franken-Frimware 0.5.1 umgeflasht (sysupgrade). Das gleiche habe 
> ich mit einer 8.xer Hardware auch getan (Router km001 [8.x] und km010 
> [9.0] https://netmon.freifunk-franken.de/router.php?router_id=1647) 
> Bei der 8.xer Hardware gab es keine Probleme.
>
> Der 9.0er wurde problemlos im Netmon aufgenommen, und meshte. Jedoch 
> war das einloggen ins WLAN mit einem Client nicht möglich. Allem 
> Anschein nach wurde keine IP vergeben.
>
> Ein Downgrade auf 0.5.0 scheint Abhilfe geschaffen zu haben.
>
> Kann jemand den Fehler bestätigen oder dürfte es sich um ein 
> Hardwareproblem handeln?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreifunkFranken/firmware/issues/27>.
>
hi

bitte nach dem Update nochmal händisch neu booten (entweder im ssh 
reboot eingeben oder Stecker ziehen). Manche Router brauchen dann 
anschließend u.U. nochmal ein paar Gedenkminuten, warum weshalb weiß ich 
nicht aber hilft dann meistens ;) (oft kommt auf meine Antwort dies zu 
tun schon als antwort zurück das es schon wieder geht ;) ) Auch hatte 
ich jetzt schon den Fall, das sie einige Zeit lang im Netmon als Offline 
auftauchen (obwohl sie ansonsten problemlos gehen) bevor sich netmon 
doch irgendwann entschließt die Teile als Online anzuzeigen, warum 
weshalb ???

mfg

Christian

-- 
Kontaktmöglichkeiten ChristianD (Christian Dresel):
Jabber: christian@jabber.community
E-Mail: fff@chrisi01.de
Facebook: https://www.facebook.com/christian.chili
Handy/Whatsapp & Festnetz: auf Nachfrage

**Comment by ChristianDresel** [comment]
Am 06.11.2015 um 21:14 schrieb Jonas Schwemmer:
>
> Ich habe hier das selbe Problem, seit ca. einer Woche bekommen 
> Endgeräte keine IP mehr. Das Problem besteht bei mir an den Routern 
> "KJBuehl1" und "RZK5", beides WRD1043nd Rev. 2.1 Zeit zum gucken woran 
> es liegen könnte, hatte ich bisher leider nicht.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreifunkFranken/firmware/issues/27#issuecomment-154520501>.
>
Was ich gerade sehe, alle Router in der Erlangener Hood, an die dortigen 
Gatewaybetreiber, ist bei euch Batman Gateway Selection schon aktiv? Ich 
bin mir jetzt nicht mehr sicher aber wenn kein GW mit aktiven 
Gatewayselection in der Hood ist, kann es dann sein das die 0.5.1. keine 
IPs mehr raus gibt/geben kann? Bitte berichtigen wenn falsch, Danke.

mfg

Christian

-- 
Kontaktmöglichkeiten ChristianD (Christian Dresel):
Jabber: christian@jabber.community
E-Mail: fff@chrisi01.de
Facebook: https://www.facebook.com/christian.chili
Handy/Whatsapp & Festnetz: auf Nachfrage

**Comment by jonasbebe** [comment]
Direkt nach dem Update hatte es aber funktioniert. (bilde ich mir jedenfalls ein ;-) )

**Comment by ChristianDresel** [comment]
Ich habe heute auch zwei neue Router mit der Firmware 0.5.1 geflasht und
bekam dann keine IP-Adresse zugewiesen, in der Hood Erlangen.

Übrigens, über das Gateway fff-gw-yaga ist in der Hood Erlangen keine
Internet-Telefonie möglich, über das Gateway nue1.freifunk-franken.de schon.

Gruß, "Radiator"

Am 6. November 2015 um 21:41 schrieb Christian Dresel <fff@chrisi01.de>:

> Am 06.11.2015 um 21:14 schrieb Jonas Schwemmer:
>
> Ich habe hier das selbe Problem, seit ca. einer Woche bekommen Endgeräte
> keine IP mehr. Das Problem besteht bei mir an den Routern "KJBuehl1" und
> "RZK5", beides WRD1043nd Rev. 2.1 Zeit zum gucken woran es liegen könnte,
> hatte ich bisher leider nicht.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreifunkFranken/firmware/issues/27#issuecomment-154520501>
> .
>
> Was ich gerade sehe, alle Router in der Erlangener Hood, an die dortigen
> Gatewaybetreiber, ist bei euch Batman Gateway Selection schon aktiv? Ich
> bin mir jetzt nicht mehr sicher aber wenn kein GW mit aktiven
> Gatewayselection in der Hood ist, kann es dann sein das die 0.5.1. keine
> IPs mehr raus gibt/geben kann? Bitte berichtigen wenn falsch, Danke.
>
> mfg
>
> Christian
>
> --
> Kontaktmöglichkeiten ChristianD (Christian Dresel):
> Jabber: christian@jabber.community
> E-Mail: fff@chrisi01.de
> Facebook: https://www.facebook.com/christian.chili
> Handy/Whatsapp & Festnetz: auf Nachfrage
>
>
> --
> franken-dev mailing list
> franken-dev@freifunk.net
> http://lists.freifunk.net/mailman/listinfo/franken-dev-freifunk.net
>
>
-- 
**********************************************************
Michael Kreis, Hardstr. 35, 90766 Fürth, Allemagne/Germany
mailto:Michael.Kreis@gmail.com
**********************************************************

**Comment by luwimi** [comment]
Der bei mir instabile Knoten (km010) wurde mehrfach auch hardwareseitig rebootet, ohne dass dieses Auswirkungen gehabt hätte.

Allgemein habe ich beobachtet, dass nach einem Upgrade ein Hardwarereset erforderlich ist, da ansonsten der Datendurchsatz bei den Clients gering ausfällt.

**Comment by ChristianDresel** [comment]
Hi Christian

Ich hab eben geschaut, auf fff_nue1 war die gw selection tatsächlich
aus. :/ Muss mir bei Zeiten das Starten des Scripts nochmal angucken.

Tim

Am Freitag, den 06.11.2015, 21:41 +0100 schrieb Christian Dresel:

**Comment by skyYaga** [comment]
Servus, 

ich schau mir die Tage mal an, warum die Telefonie über fff-gw-yaga nicht funktioniert. 

Viele Grüße 
Yaga 

Am 6. November 2015 22:59:00 MEZ, schrieb ChristianDresel <notifications@github.com>:

**Comment by ChristianDresel** [comment]
kannst auch für eine schnelle Lösung erst mal ein

batctl gw_mode server 100Mbit/100Mbit

machen (bitte Syntax nochmal prüfen) dann bekommen die Leute zumindest 
eine IP.

mfg

Christian


Am 06.11.2015 um 22:58 schrieb Tim Niemeyer:
> Hi Christian
>
> Ich hab eben geschaut, auf fff_nue1 war die gw selection tatsächlich
> aus. :/ Muss mir bei Zeiten das Starten des Scripts nochmal angucken.
>
> Tim
>
> Am Freitag, den 06.11.2015, 21:41 +0100 schrieb Christian Dresel:
>> Am 06.11.2015 um 21:14 schrieb Jonas Schwemmer:
>>
>>> Ich habe hier das selbe Problem, seit ca. einer Woche bekommen
>>> Endgeräte keine IP mehr. Das Problem besteht bei mir an den Routern
>>> "KJBuehl1" und "RZK5", beides WRD1043nd Rev. 2.1 Zeit zum gucken
>>> woran es liegen könnte, hatte ich bisher leider nicht.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub.
>>>
>>>
>> Was ich gerade sehe, alle Router in der Erlangener Hood, an die
>> dortigen Gatewaybetreiber, ist bei euch Batman Gateway Selection schon
>> aktiv? Ich bin mir jetzt nicht mehr sicher aber wenn kein GW mit
>> aktiven Gatewayselection in der Hood ist, kann es dann sein das die
>> 0.5.1. keine IPs mehr raus gibt/geben kann? Bitte berichtigen wenn
>> falsch, Danke.
>>
>> mfg
>>
>> Christian
>>
>> -- 
>> Kontaktmöglichkeiten ChristianD (Christian Dresel):
>> Jabber: christian@jabber.community
>> E-Mail: fff@chrisi01.de
>> Facebook: https://www.facebook.com/christian.chili
>> Handy/Whatsapp & Festnetz: auf Nachfrage
>> -- 
>> franken-dev mailing list
>> franken-dev@freifunk.net
>> http://lists.freifunk.net/mailman/listinfo/franken-dev-freifunk.net


-- 
Kontaktmöglichkeiten ChristianD (Christian Dresel):
Jabber: christian@jabber.community
E-Mail: fff@chrisi01.de
Facebook: https://www.facebook.com/christian.chili
Handy/Whatsapp & Festnetz: auf Nachfrage

**Comment by ChristianDresel** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi

Am 6. November 2015 23:19:21 MEZ, schrieb Christian Dresel <fff@chrisi01.de>:
>kannst auch für eine schnelle Lösung erst mal ein
>
>batctl gw_mode server 100Mbit/100Mbit
>
>machen (bitte Syntax nochmal prüfen) dann bekommen die Leute zumindest
>eine IP.

Der sollte jetzt allerdings schon richtig laufen.

Tim
>
>mfg
>
>Christian
>
>
>Am 06.11.2015 um 22:58 schrieb Tim Niemeyer:
>> Hi Christian
>>
>> Ich hab eben geschaut, auf fff_nue1 war die gw selection tatsächlich
>> aus. :/ Muss mir bei Zeiten das Starten des Scripts nochmal angucken.
>>
>> Tim
>>
>> Am Freitag, den 06.11.2015, 21:41 +0100 schrieb Christian Dresel:
>>> Am 06.11.2015 um 21:14 schrieb Jonas Schwemmer:
>>>
>>>> Ich habe hier das selbe Problem, seit ca. einer Woche bekommen
>>>> Endgeräte keine IP mehr. Das Problem besteht bei mir an den Routern
>>>> "KJBuehl1" und "RZK5", beides WRD1043nd Rev. 2.1 Zeit zum gucken
>>>> woran es liegen könnte, hatte ich bisher leider nicht.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub.
>>>>
>>>>
>>> Was ich gerade sehe, alle Router in der Erlangener Hood, an die
>>> dortigen Gatewaybetreiber, ist bei euch Batman Gateway Selection
>schon
>>> aktiv? Ich bin mir jetzt nicht mehr sicher aber wenn kein GW mit
>>> aktiven Gatewayselection in der Hood ist, kann es dann sein das die
>>> 0.5.1. keine IPs mehr raus gibt/geben kann? Bitte berichtigen wenn
>>> falsch, Danke.
>>>
>>> mfg
>>>
>>> Christian
>>>
>>> --
>>> Kontaktmöglichkeiten ChristianD (Christian Dresel):
>>> Jabber: christian@jabber.community
>>> E-Mail: fff@chrisi01.de
>>> Facebook: https://www.facebook.com/christian.chili
>>> Handy/Whatsapp & Festnetz: auf Nachfrage
>>> --
>>> franken-dev mailing list
>>> franken-dev@freifunk.net
>>> http://lists.freifunk.net/mailman/listinfo/franken-dev-freifunk.net
-----BEGIN PGP SIGNATURE-----

iQFIBAEBCgAyKxxUaW0gTmllbWV5ZXIgPHRpbS5uaWVtZXllckBtYXN0ZXJzd29y
ZC5kZT4FAlY9KGsACgkQELiw0DPkKM/Pgwf+I6UyfmReDQm7yU5bODNvH/LKfz/q
rrwqNYpsSwx0j6II9lFa+HoiJThq+dGqtBLplrarqTlA4KWuAo6TRQWSjFRIb1PV
YMixkqYcG5eIPiIe0sDTkplnsiEu9hISSmCc+jTEThKjemJ0lgdA87tLFdg+MbST
HgyDkPqtrbgPQy+CHqMpvkch1fmlamkpBak3VgYQgGAVMRncfQh/zVYjj2zO+hD7
ZACd6+YEifg6SlZpl5nqdmUpPSH/T6TsivW9iqKwvfeZL7EdHR+JKCpZdVjqBITq
pQOYO96bgt/hjUrT0i/x6tZQmzxdvWMK5NSCFGtSoIvdWWYIIG3F+s/v/w==
=8wV9
-----END PGP SIGNATURE-----
