### ISSUE TITLE
Images umbenennen

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/firmware#9]
Die Images sollten "schönere" Dateinahmen haben.

z.B. statt
`openwrt-ar71xx-generic-tl-wr1043nd-v1-squashfs-factory.bin`
sowas:
`fff_tl-wr1043nd-v1_0.5.0_factory.bin`

**Comment by kratz00** [comment]
https://github.com/FreifunkFranken/firmware/commit/ff7e8b7a6664c8247a635c1d92cf5d5c6928de58
